# hey, this looks a lot like Exhibitor.objects.all().values()
#    {
#        'username': '',
#        'password': 'password',
#        'first_name': '',
#        'last_name': '',
#        'email': '',
#        'company': '',
#        'website': '',
#        'address': '',
#        'address2': '',
#        'city': '',
#        'state': '',
#        'zip': '',
#        'phone': '',
#        'fax': '',
#        'lines': """ """,
#    },
exhibitors = [
    {
        'username': 'testex',
        'password': 'testex',
        'first_name': 'Test',
        'last_name': 'Exhibitor',
        'email': 'info@nwkidsshow.com',
        'company': 'Laurel Event Management',
        'website': 'http://www.nwkidsshow.com/',
        'address': '17565 SW 108th place',
        'address2': '',
        'city': 'Tualatin',
        'state': 'OR',
        'zip': '97062',
        'phone': '503-330-7167',
        'fax': '503-555-1212',
        'lines': """no * lines * really""",
    },
    {
        'username': 'allison_acken',
        'password': 'password',
        'first_name': 'Allison',
        'last_name': 'Acken',
        'email': 'allisonshowroom@gmail.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '310-486-9354',
        'fax': '',
        'lines': """Kanz * Wheat * Purebaby Organic * Finn and Emma Organic""",
    },
    {
        'username': 'randee_arneson',
        'password': 'password',
        'first_name': 'Randee',
        'last_name': 'Arneson',
        'email': 'randeesshowroom@gmail.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '213-624-8422',
        'fax': '213-624-8946',
        'lines': """Petit Lem * Me Too * Losan * Blueberry Hill * Melton * Monkeybar Buddies * Nosilla Organics * She's the One * Thingamajiggies, PJ's * Marmalade * Ollie Baby * Nadi A Biffi * Imagine Greenwear * Rose Cage * Everbloom Studio * Polka Dot Moon * Milla Reese Hair accessories * Toni Tierney""",
    },
    {
        'username': 'nancy_camus',
        'password': 'password',
        'first_name': 'Nancy',
        'last_name': 'Camus',
        'email': 'info@paperdollstyleshowroom.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-629-9874',
        'fax': '213-629-9875',
        'lines': """Chibella * Livie & Luca * Feather Baby * The Happy Closet * Decaf Plush * Just Fab Girls * Smile Squared""",
    },
    {
        'username': 'jack_chapman',
        'password': 'password',
        'first_name': 'Jack',
        'last_name': 'Chapman',
        'email': 'jackc@net-venture.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'University Place',
        'state': 'WA',
        'zip': '',
        'phone': '253-235-1870',
        'fax': '',
        'lines': """Just Be * Worry Woos * Our Globo * Robot Luv * Stikiis""",
    },
    {
        'username': 'helene_cohen',
        'password': 'password',
        'first_name': 'Helene',
        'last_name': 'Cohen',
        'email': 'toohotusa@aol.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-627-5773',
        'fax': '213-629-2479',
        'lines': """Lazy One Sleep Wear * Sozo * Agabang * Happy Mermaid Dresses * Boker & Laila Pajamas * Zopheez * 2 Red Hens * Mini zzz * Sovereign * Tortle Hats""",
    },
    {
        'username': 'nicky_coscas',
        'password': 'password',
        'first_name': 'Nicky',
        'last_name': 'Coscas',
        'email': 'nicky@nickyrosekids.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '213-593-1322   ',
        'fax': '213-593-1323',
        'lines': """7 For All Mankind Kids * City Threads * Egg by Susan Lazar * Juicy Couture Baby * Kiniki * LA Made kids * Ode * PAIGELAUREN baby * The Green Egg""",
    },
    {
        'username': 'susie_cinningham',
        'password': 'password',
        'first_name': 'Susie',
        'last_name': 'Cunningham',
        'email': 'susiesunkid@yahoo.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Portland',
        'state': 'OR',
        'zip': '',
        'phone': '503-230-1219',
        'fax': '503-231-3554',
        'lines': """Roxy Girl * Roxy Teenie Wahine * Quiksilver Boys & Baby * Country Kids Legwear * No Slippy Hair Clippy""",
    },
    {
        'username': 'gloria_davis',
        'password': 'password',
        'first_name': 'Gloria',
        'last_name': 'Davis',
        'email': 'gloriapdavis@sbcglobal.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'San Francisco',
        'state': 'CA',
        'zip': '',
        'phone': '415-297-3906',
        'fax': '888-511-6990',
        'lines': """SnoPea, Inc. * Preemie Yums * Mack & Co. * Two Flowers One Bear * Bear Hands & Buddies * Million Polkadots""",
    },
    {
        'username': 'linsey_ebuen',
        'password': 'password',
        'first_name': 'Linsey',
        'last_name': 'Ebuen',
        'email': 'linsey.ebuen@guavakids.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Beaverton',
        'state': 'OR',
        'zip': '',
        'phone': '503-327-4868',
        'fax': '888-946-4828',
        'lines': """GuavaKids""", #TODO: test this! one entry, no delimiters.
    },
    {
        'username': 'joann_farese',
        'password': 'password',
        'first_name': 'JoAnn',
        'last_name': 'Farese',
        'email': 'j_farese@sbcglobal.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'San Francisco',
        'state': 'CA',
        'zip': '',
        'phone': '415-742-5422',
        'fax': '415-661-2296',
        'lines': """Crocs Kids Apparel * Crocs Accessories * Colette Kids * Girl & Co. * Lime Apple * New Jammies * Origany * Real Kids Shades * Wayi Bamboo * Wugbug * Breganwood Organics * Shinobi Baby""",
    },
    {
        'username': 'afton_farley',
        'password': 'password',
        'first_name': 'Afton',
        'last_name': 'Farley',
        'email': 'afton@redwagonbaby.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '310-569-0366',
        'fax': '',
        'lines': """Red Wagon Baby * June Kids""",
    },
    {
        'username': 'sylvia_gill',
        'password': 'password',
        'first_name': 'Sylvia',
        'last_name': 'Gill',
        'email': 'showroom@sylviagill.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'San Francisco',
        'state': 'CA',
        'zip': '',
        'phone': '415-255-9899',
        'fax': '415-255-9929',
        'lines': """Kissy Kissy * Newborn by Mayoral * Mulberribush * Love U Lots * Down East Girls * Haven Girl * Little Handprint * Lollipop Twirl * Flap Happy * Zoocchini * Bows Arts * Konfetti * Kai Kreations * Ragtop - Neptune Zoo""",
    },
    {
        'username': 'sandra_gorecke',
        'password': 'password',
        'first_name': 'Sandra',
        'last_name': 'Gorecke',
        'email': 'showroomalamode@gmail.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-393-7097',
        'fax': '213-995-9862',
        'lines': """I DO * Mini banda * Sarrabanda * Silvian Heach * Imoga * Bari Lynn hair accessories * Tutim NYC""",
    },
    {
        'username': 'angela_hansen',
        'password': 'password',
        'first_name': 'Angela',
        'last_name': 'Grosvenor Hansen',
        'email': 'evergreenrep@frontier.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Duvall',
        'state': 'WA',
        'zip': '',
        'phone': '425-844-1431',
        'fax': '425-844-1431',
        'lines': """Babalu * Baby Buddha Studio * Bunnies by the Bay * Creative Education * Do A Dot * Eco Kids * Elope * Endangered Species * European Expressions * Fish River Crafts * GeoToys * Groovy Holidays * Independent Pub Group * Just Jump It * KaZAM Bikes * Kid's Preferred * Kiss Naturals * Klein * Klean Kanteen * Legendary Games * Light-Beams * Magic Forest * Maxim Enterprises * Meadowview Imports * Mindtwister USA * minina * Moonjar * Pacific Play Tent * Piggy Paint * ReUsies * Sentosphere * TWC of America * Ulubulu * Uncle Goose * Warm Fuzzy * WoolPets""",
    },
    {
        'username': 'betsy_harney',
        'password': 'password',
        'first_name': 'Betsy',
        'last_name': 'Harney',
        'email': 'contact@sugarbsales.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Renton',
        'state': 'WA',
        'zip': '',
        'phone': '425-277-5499',
        'fax': '800-783-9875',
        'lines': """Dabbawalla Bags * Douglas Company * eeBoo * Jack Rabbit * Kid Style * Lunch Bots * Merry Makers * P'Kolino * Rich Frog * Tullie Girl""",
    },
    {
        'username': 'tanya_hawkins',
        'password': 'password',
        'first_name': 'Tanya',
        'last_name': 'Hawkins',
        'email': 'monkeybizreps@gmail.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Portland',
        'state': 'OR',
        'zip': '',
        'phone': '503-799-6221',
        'fax': '503-244-9914',
        'lines': """Petunia Pickle Bottom * See Kai Run * Trumpette * Bebe au lait * Magnificent Baby * Minnie & Lola * Zootie B Little * Giddy Giddy * Noodle & Boo * Crawlings * Tadpole & Lily * Via Cacao""",
    },
    {
        'username': 'cristy_howe',
        'password': 'password',
        'first_name': 'Cristy',
        'last_name': 'Howe',
        'email': 'cristy@teacollection.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '805-746-4985',
        'fax': '415-321-2478',
        'lines': """Tea Collection""", # TODO test this with one entry
    },
    {
        'username': 'judy_johnson',
        'password': 'password',
        'first_name': 'Judy',
        'last_name': 'Johnson',
        'email': 'jj.sales@comcast.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Portland',
        'state': 'OR',
        'zip': '',
        'phone': '503-246-5707',
        'fax': '503-452-8840',
        'lines': """ """, # TODO test this with NO entries
    },
    {
        'username': 'sarah_kaufman',
        'password': 'password',
        'first_name': 'Sarah',
        'last_name': 'Kaufman',
        'email': 'sarahco@att.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'San Francisco',
        'state': 'CA',
        'zip': '',
        'phone': '415-379-4400',
        'fax': '415-379-4341',
        'lines': """Le Top * Le Top Baby * Rabbitmoon* Hartstrings * KC Parker * Wee Ones * Pluie Pluie Rainwear * Foxfire Rainwear * Tuff Kookooshka * Apollo sock & tights * David Fussenegger blankets * L'Amour shoes * Knot Genie""",
    },
    {
        'username': 'july_krause',
        'password': 'password',
        'first_name': 'July',
        'last_name': 'Krause',
        'email': 'wendyscloset@gmail.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-627-9506',
        'fax': '213-627-8695',
        'lines': """Winter Water Factory * Nano * Lily and Momo * Sweet Peanut * Ooh La La Couture * Luna Leggings * Persnickety Clothing * Silkberry Baby * IDA - T Denmark * Shampoodle * Joyfolie Shoes * Liv & Lily * Chewbeads * Old Soles Shoes * NOHI Organics""",
    },
    {
        'username': 'betty_lewis',
        'password': 'password',
        'first_name': 'Betty',
        'last_name': 'Lewis',
        'email': 'betty@bettylewissales.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Lakebay',
        'state': 'WA',
        'zip': '',
        'phone': '888-732-6103',
        'fax': '866-902-1401',
        'lines': """i Play/green sprouts * Kushies Basics * Halo Innovations * Sock Ons * Baby Jogger * Recaro Car Seats * Moonlight Slumber * 4moms""",
    },
    {
        'username': 'sandra_martinez',
        'password': 'password',
        'first_name': 'Sandran',
        'last_name': 'Martinez',
        'email': 'info@inplayshowroom.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-489-7908',
        'fax': '',
        'lines': """Appaman * Chaser Kids * Diaper Dude * Me In Mind * Native Shoes * Mini Maniacs Bibs * Modern Lux (Tween) * Prefresh""",
    },
    {
        'username': 'leslie_nielsen',
        'password': 'password',
        'first_name': 'Leslie',
        'last_name': 'Nielsen',
        'email': 'lesniel@comcast.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Seattle',
        'state': 'WA',
        'zip': '',
        'phone': '206-937-6013',
        'fax': '206-937-1778',
        'lines': """Mimi & Maggie * Angel Dear * Little Sea Gems * Chooze Shoes * Huggalugs""",
    },
    {
        'username': 'bob_parrish',
        'password': 'password',
        'first_name': 'Bob',
        'last_name': 'Parrish',
        'email': 'bobparrish@sbcglobal.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Martinez',
        'state': 'CA',
        'zip': '',
        'phone': '925-228-5696',
        'fax': '925-228-5699',
        'lines': """Isobella & Chloe * Dogwood * Betty Ann Hats * Milsky Belts * Elegantbaby * Peaceable Kingdom * Purple Mountains Ice Caps & Hats * Pickles Footwear * Squeak-Me-Shoes * Plum/Plum Pudding * Pink Ginger * Up and Away Jackets * Bonne * La Piccola Danza""",
    },
    {
        'username': 'colleen_post',
        'password': 'password',
        'first_name': 'Colleen',
        'last_name': 'Post',
        'email': 'postc@comcast.net',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Tigard',
        'state': 'OR',
        'zip': '',
        'phone': '503-579-2409',
        'fax': '503-590-8198',
        'lines': """Under the Nile * Beba Bean * Wry Baby * Funkie Baby * Kiwi""",
    },
    {
        'username': 'robert_prescott',
        'password': 'password',
        'first_name': 'Robert',
        'last_name': 'Prescott',
        'email': 'rd@youngcolors.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Salida',
        'state': 'CO',
        'zip': '',
        'phone': '719-539-3812',
        'fax': '719-539-3813',
        'lines': """Young Colors * Frumpy Rumps *Silly Sarongs * Young Colors Hats * College Colors""",
    },
    {
        'username': 'julie_smith',
        'password': 'password',
        'first_name': 'Julie',
        'last_name': 'Smith',
        'email': 'julie@juliesmithkids.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-622-4643',
        'fax': '213-622-7451',
        'lines': """Mayoral * Urban Sunday * Yosi Samra Shoes * Ciao Marco * Zutano * Timi and Leslie * Little Joules * M. Andonia * Sossabella Jewelry * Laundry by Shelli Segal""",
    },
    {
        'username': 'teresa_stephen',
        'password': 'password',
        'first_name': 'Teresa',
        'last_name': 'Stephen',
        'email': 'krystal@teresasroom.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '866-723-5437',
        'fax': '213-612-0227',
        'lines': """Little Me * Offspring * Nannette * Popatu by Posh Int'l. * Peaches'n Cream * Mallory May * Mollie & Millie * Guess Kids * Flapdoodles * Wee Squeak Shoes * Tommy Tickle * Bobux * AM PM Kids * Fancy That Hat * Hide-ees * Kensie Girl * Fun Apparel""",
    },
    {
        'username': 'joanne_torres',
        'password': 'password',
        'first_name': 'Joanne',
        'last_name': 'Torres',
        'email': 'showroom@lolajosales.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-623-0993',
        'fax': '213-244-9645',
        'lines': """New ICM/Laura Dare * Little Adventures * Max Daniel Blankets * Luli and Me * Hello Kitty * Baby Bling * Sara Kety * Julius Berger * Malibu Swimwear * Ska Doo Shoes * Carriage Boutique * Boutique Collection * Feltman * Toe Blooms * Woolrich * Drench Raingear * Baby Buns""",
    },
    {
        'username': 'cathe_verdusco',
        'password': 'password',
        'first_name': 'Cathe',
        'last_name': 'Verdusco',
        'email': 'jody@smallshopshowroom.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-488-0090',
        'fax': '213-488-0040',
        'lines': """Charlie Rocket * Desigual * Maisonette * Mini & Maximus * Shwings * Milk & Soda * Curio & Kind * La Piccola Danza * Big Citizen * SuperTrash""",
    },
    {
        'username': 'don_welborn',
        'password': 'password',
        'first_name': 'Don',
        'last_name': 'Welborn',
        'email': 'sales@donwelborn.com',
        'company': '',
        'website': '',
        'address': '',
        'address2': '',
        'city': 'Los Angeles',
        'state': 'CA',
        'zip': '',
        'phone': '213-688-4953',
        'fax': '213-688-0165',
        'lines': """Vitamins Baby * Absorba * Kushies * Zaza Couture * Donita * Intakt * Kids Republic Dx Xtreme * Trimfit * Globaltex Kids * Ben Sherman * French Connection * Firetrap""",
    },
]

