#    {
#        'username': '',
#        'password': 'password',
#        'first_name': '',
#        'last_name': '',
#        'email': '',
#        'company': '',
#        'website': '',
#        'address': '',
#        'address2': '',
#        'city': '',
#        'state': '',
#        'zip': '',
#        'phone': '',
#        'fax': '',
#        },
retailers = [
    {
        'username': 'testre',
        'password': 'testre',
        'first_name': 'Test',
        'last_name': 'Retailer',
        'email': 'info@nwkidsshow.com',
        'company': 'Laurel Event Management',
        'website': 'http://www.nwkidsshow.com/',
        'address': '17565 SW 108th Place',
        'address2': '',
        'city': 'Tualatin',
        'state': 'OR',
        'zip': '97062',
        'phone': '503-330-7167',
        'fax': '503-555-1212',
    },
    {
        # ['A Liengboonlertchai', 'Simplicity ABC', 'info@simplicityabc.com', '425-250-1186', '', '']
        'username': 'a_liengboonlertchai',
        'password': 'password',
        # A Liengboonlertchai,
        'first_name': 'A',
        'last_name': 'Liengboonlertchai',
        'email': 'info@simplicityabc.com',
        'company': 'Simplicity ABC',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-250-1186',
        'fax': '',
    },
    {
        # ['Alli Azevedo Megan Lynch', 'Black Wagon', 'sales@blackwagon.com', '503-916-0000', '', '']
        'username': 'alli_azevedo',
        'password': 'password',
        # Alli Azevedo Megan Lynch,
        'first_name': 'Alli',
        'last_name': 'Azevedo',
        'email': 'sales@blackwagon.com',
        'company': 'Black Wagon',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-916-0000',
        'fax': '',
    },
    {
        # ['Amy Malave', 'Beachside Gifts', 'bpgutmann@aol.com', '360-598-4980', '', '']
        'username': 'amy_malave',
        'password': 'password',
        # Amy Malave,
        'first_name': 'Amy',
        'last_name': 'Malave',
        'email': 'bpgutmann@aol.com',
        'company': 'Beachside Gifts',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-598-4980',
        'fax': '',
    },
    {
        # ['Amy Sible', 'Skagit Valley Food Co-Op', 'merc@skagitfoodcoop.com', '360-336-5087x123', '', '']
        'username': 'amy_sible',
        'password': 'password',
        # Amy Sible,
        'first_name': 'Amy',
        'last_name': 'Sible',
        'email': 'merc@skagitfoodcoop.com',
        'company': 'Skagit Valley Food Co-Op',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-336-5087x123',
        'fax': '',
    },
    # {
    #     # ['Ann', "L's on Augusta", 'amigracco@hotmail.com', '864-232-4022', '', '']
    #     'username': 'ann',
    #     'password': 'password',
    #     # Ann,
    #     'first_name': 'Ann',
    #     'last_name': 'Ann',
    #     'email': 'amigracco@hotmail.com',
    #     'company': "L's on Augusta",
    #     'website': '',
    #     'address': '',
    #     'address2': '',
    #     'city': '',
    #     'state': '',
    #     'zip': '',
    #     'phone': '864-232-4022',
    #     'fax': '',
    # },
    {
        # ['Barbara Robert', 'Charlie Barnes', 'michelle@charliebarneskids.com', '253-509-0449', '', '']
        'username': 'barbara_robert',
        'password': 'password',
        # Barbara Robert,
        'first_name': 'Barbara',
        'last_name': 'Robert',
        'email': 'michelle@charliebarneskids.com',
        'company': 'Charlie Barnes',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '253-509-0449',
        'fax': '',
    },
    {
        # ['Bianca Newbott', 'Bratz in Vogue', 'bianca@bratzinvogue.com', '360-200-1786', '', '']
        'username': 'bianca_newbott',
        'password': 'password',
        # Bianca Newbott,
        'first_name': 'Bianca',
        'last_name': 'Newbott',
        'email': 'bianca@bratzinvogue.com',
        'company': 'Bratz in Vogue',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-200-1786',
        'fax': '',
    },
    {
        # ['Bob Pressey', 'Merry-Go-Round', 'info@merrygoroundkids.com', '425-454-1610', '425-451-8724', '']
        'username': 'bob_pressey',
        'password': 'password',
        # Bob Pressey,
        'first_name': 'Bob',
        'last_name': 'Pressey',
        'email': 'info@merrygoroundkids.com',
        'company': 'Merry-Go-Round',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-454-1610',
        'fax': '425-451-8724',
    },
    {
        # ['Brigid Rossolo', 'Teton Kids', 'tetonkidswy@aol.com', '307-739-2176', '307-733-9617', '']
        'username': 'brigid_rossolo',
        'password': 'password',
        # Brigid Rossolo,
        'first_name': 'Brigid',
        'last_name': 'Rossolo',
        'email': 'tetonkidswy@aol.com',
        'company': 'Teton Kids',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '307-739-2176',
        'fax': '307-733-9617',
    },
    {
        # ['Carmen Bullard', 'Carmelita', 'carmenking23@gmail.com', '206-999-3071', '', '']
        'username': 'carmen_bullard',
        'password': 'password',
        # Carmen Bullard,
        'first_name': 'Carmen',
        'last_name': 'Bullard',
        'email': 'carmenking23@gmail.com',
        'company': 'Carmelita',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-999-3071',
        'fax': '',
    },
    {
        # ['Cathy Aller', 'Boston Street', 'c.aller@comcast.net', '206-634-0580', '', '']
        'username': 'cathy_aller',
        'password': 'password',
        # Cathy Aller,
        'first_name': 'Cathy',
        'last_name': 'Aller',
        'email': 'c.aller@comcast.net',
        'company': 'Boston Street',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-634-0580',
        'fax': '',
    },
    {
        # ['Chalese Smartt', 'Tiny Soles', 'sales@tinysoles.com', '360-458-5600', '', '']
        'username': 'chalese_smartt',
        'password': 'password',
        # Chalese Smartt,
        'first_name': 'Chalese',
        'last_name': 'Smartt',
        'email': 'sales@tinysoles.com',
        'company': 'Tiny Soles',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-458-5600',
        'fax': '',
    },
    {
        # ['Christine Bolt', 'Posh Baby', 'accounting@poshbaby.com', '503-478-7674', '503-228-8600', '']
        'username': 'christine_bolt',
        'password': 'password',
        # Christine Bolt,
        'first_name': 'Christine',
        'last_name': 'Bolt',
        'email': 'accounting@poshbaby.com',
        'company': 'Posh Baby',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-478-7674',
        'fax': '503-228-8600',
    },
    {
        # ['Cindy Ludwig', 'The Corner Shop Swedish Medical Center', 'cindy.ludwig@swedish.org', '206-386-2466', '', '']
        'username': 'cindy_ludwig',
        'password': 'password',
        # Cindy Ludwig,
        'first_name': 'Cindy',
        'last_name': 'Ludwig',
        'email': 'cindy.ludwig@swedish.org',
        'company': 'The Corner Shop Swedish Medical Center',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-386-2466',
        'fax': '',
    },
    {
        # ['Connie Hartman', 'Small Change', 'connie@smallchangeashland.com', '541-488-1000', '', '']
        'username': 'connie_hartman',
        'password': 'password',
        # Connie Hartman,
        'first_name': 'Connie',
        'last_name': 'Hartman',
        'email': 'connie@smallchangeashland.com',
        'company': 'Small Change',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '541-488-1000',
        'fax': '',
    },
    {
        # ['Cressie Baerg', 'Perfectly Preemie', 'cressie@perfectlypreemie.com', '505-433-1958', '', '']
        'username': 'cressie_baerg',
        'password': 'password',
        # Cressie Baerg,
        'first_name': 'Cressie',
        'last_name': 'Baerg',
        'email': 'cressie@perfectlypreemie.com',
        'company': 'Perfectly Preemie',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '505-433-1958',
        'fax': '',
    },
    {
        # ['David Bremner', "Bubba Loo Children's Boutique", 'kdbremner@shaw.ca', '250 655-7270', '', '']
        'username': 'david_bremner',
        'password': 'password',
        # David Bremner,
        'first_name': 'David',
        'last_name': 'Bremner',
        'email': 'kdbremner@shaw.ca',
        'company': "Bubba Loo Children's Boutique",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '250 655-7270',
        'fax': '',
    },
    {
        # ['Desmond & Kim Wong', 'Lambs Ears', 'lambsears_wa@yahoo.com', '425-467-1112', '', '']
        'username': 'desmond_wong',
        'password': 'password',
        # Desmond & Kim Wong,
        'first_name': 'Desmond',
        'last_name': 'Wong',
        'email': 'lambsears_wa@yahoo.com',
        'company': 'Lambs Ears',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-467-1112',
        'fax': '',
    },
    {
        # ['Dianna Bodin', 'Baby-n-Me', 'sandy@babynme.comcastbiz.net', '360-675-8816', '', '']
        'username': 'dianna_bodin',
        'password': 'password',
        # Dianna Bodin,
        'first_name': 'Dianna',
        'last_name': 'Bodin',
        'email': 'sandy@babynme.comcastbiz.net',
        'company': 'Baby-n-Me',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-675-8816',
        'fax': '',
    },
    # {
    #     # ['Dianna Lagervall', 'Kinder Britches', 'dianna@kinderbritches.com', '425-778-7600', '', '']
    #     'username': 'dianna_lagervall',
    #     'password': 'password',
    #     # Dianna Lagervall,
    #     'first_name': 'Dianna',
    #     'last_name': 'Lagervall',
    #     'email': 'dianna@kinderbritches.com',
    #     'company': 'Kinder Britches',
    #     'website': '',
    #     'address': '',
    #     'address2': '',
    #     'city': '',
    #     'state': '',
    #     'zip': '',
    #     'phone': '425-778-7600',
    #     'fax': '',
    # },
    {
        # ['Donna DeRousie', 'City Mouse', 'dderousie@comcast.net', '206-937-1554', '', '']
        'username': 'donna_derousie',
        'password': 'password',
        # Donna DeRousie ,
        'first_name': 'Donna',
        'last_name': 'DeRousie',
        'email': 'dderousie@comcast.net',
        'company': 'City Mouse',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-937-1554',
        'fax': '',
    },
    {
        # ['Ellie Cassidy', 'Bootyland', 'info@bootylandkids.com', '206-328-0636', '', '']
        'username': 'ellie_cassidy',
        'password': 'password',
        # Ellie Cassidy,
        'first_name': 'Ellie',
        'last_name': 'Cassidy',
        'email': 'info@bootylandkids.com',
        'company': 'Bootyland',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-328-0636',
        'fax': '',
    },
    {
        # ['Emily Kwon', 'Mini Apple Tree', 'emily@miniappletree.com', '323-384-2257', '', '']
        'username': 'emily_kwon',
        'password': 'password',
        # Emily Kwon,
        'first_name': 'Emily',
        'last_name': 'Kwon',
        'email': 'emily@miniappletree.com',
        'company': 'Mini Apple Tree',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '323-384-2257',
        'fax': '',
    },
    {
        # ['Erika Doring', 'Cutie Pie ', 'erikadoring@gorge.net', '541-436-2777', '', '']
        'username': 'erika_doring',
        'password': 'password',
        # Erika Doring,
        'first_name': 'Erika',
        'last_name': 'Doring',
        'email': 'erikadoring@gorge.net',
        'company': 'Cutie Pie ',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '541-436-2777',
        'fax': '',
    },
    {
        # ['Hannah Wampler', 'BeeGreenBaby.com LLC', 'hannah@beegreenbaby.com', '425-246-5566', '', '']
        'username': 'hannah_wampler',
        'password': 'password',
        # Hannah Wampler,
        'first_name': 'Hannah',
        'last_name': 'Wampler',
        'email': 'hannah@beegreenbaby.com',
        'company': 'BeeGreenBaby.com LLC',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-246-5566',
        'fax': '',
    },
    {
        # ['Jamie Barrigan', "Lil' Britches", 'lil4britches@earthlink.net', '503-492-9378', '503-492-9381', '']
        'username': 'jamie_barrigan',
        'password': 'password',
        # Jamie Barrigan,
        'first_name': 'Jamie',
        'last_name': 'Barrigan',
        'email': 'lil4britches@earthlink.net',
        'company': "Lil' Britches",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-492-9378',
        'fax': '503-492-9381',
    },
    {
        # ['Jana Crawford', "Whaley's General Store", 'jajoac@aol.com', '206-819-8082', '206-325-4880', '']
        'username': 'jana_crawford',
        'password': 'password',
        # Jana Crawford,
        'first_name': 'Jana',
        'last_name': 'Crawford',
        'email': 'jajoac@aol.com',
        'company': "Whaley's General Store",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-819-8082',
        'fax': '206-325-4880',
    },
    {
        # ['Janae Hoskin', 'Grow With Me Boutique', 'janae@growwithmeboutique.com', '360-794-5801', '', '']
        'username': 'janae_hoskin',
        'password': 'password',
        # Janae Hoskin,
        'first_name': 'Janae',
        'last_name': 'Hoskin',
        'email': 'janae@growwithmeboutique.com',
        'company': 'Grow With Me Boutique',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-794-5801',
        'fax': '',
    },
    {
        # ['Janet Hodgin', 'Kids NW', 'janet@kidsnorthwest.com', '360-676-6051', '', '']
        'username': 'janet_hodgin',
        'password': 'password',
        # Janet Hodgin,
        'first_name': 'Janet',
        'last_name': 'Hodgin',
        'email': 'janet@kidsnorthwest.com',
        'company': 'Kids NW',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-676-6051',
        'fax': '',
    },
    {
        # ['Janis Dean', 'The Popinjay', 'popinjay.inc@comcast.net', '360-352-9841', '360-357-9794', '']
        'username': 'janis_dean',
        'password': 'password',
        # Janis Dean,
        'first_name': 'Janis',
        'last_name': 'Dean',
        'email': 'popinjay.inc@comcast.net',
        'company': 'The Popinjay',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-352-9841',
        'fax': '360-357-9794',
    },
    {
        # ['Jenelle McCrackin', 'Once Upon A Time On Queen Ann', 'onceupontoys@live.com', '206-284-7260', '206-284-7219', '']
        'username': 'jenelle_mccrackin',
        'password': 'password',
        # Jenelle McCrackin,
        'first_name': 'Jenelle',
        'last_name': 'McCrackin',
        'email': 'onceupontoys@live.com',
        'company': 'Once Upon A Time On Queen Ann',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-284-7260',
        'fax': '206-284-7219',
    },
    {
        # ['Jenna Schlender', 'Baby & Beyond', 'lori@babyandbeyond.ca', '780-416-2188', '', '']
        'username': 'jenna_schlender',
        'password': 'password',
        # Jenna Schlender,
        'first_name': 'Jenna',
        'last_name': 'Schlender',
        'email': 'lori@babyandbeyond.ca',
        'company': 'Baby & Beyond',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '780-416-2188',
        'fax': '',
    },
    {
        # ['Jenny Bossick', 'Tiny Soles', 'sales@tinysoles.com', '360-458-5600', '', '']
        'username': 'jenny_bossick',
        'password': 'password',
        # Jenny Bossick,
        'first_name': 'Jenny',
        'last_name': 'Bossick',
        'email': 'sales@tinysoles.com',
        'company': 'Tiny Soles',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-458-5600',
        'fax': '',
    },
    {
        # ['Jenny Meyer', 'Bumblebees', 'jenjm44@hotmail.com', '360-354-1338', '', '']
        'username': 'jenny_meyer',
        'password': 'password',
        # Jenny Meyer,
        'first_name': 'Jenny',
        'last_name': 'Meyer',
        'email': 'jenjm44@hotmail.com',
        'company': 'Bumblebees',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-354-1338',
        'fax': '',
    },
    {
        # ['Jessica Ask', 'Cozy Wozy', 'askaboutcozy@gmail.com', '360-920-5546', '', '']
        'username': 'jessica_ask',
        'password': 'password',
        # Jessica Ask,
        'first_name': 'Jessica',
        'last_name': 'Ask',
        'email': 'askaboutcozy@gmail.com',
        'company': 'Cozy Wozy',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-920-5546',
        'fax': '',
    },
    {
        # ['Jessie Cordova', 'Village Maternity', 'jessie@villagematernity.com', '206-523-5167', '', '']
        'username': 'jessie_cordova',
        'password': 'password',
        # Jessie Cordova,
        'first_name': 'Jessie',
        'last_name': 'Cordova',
        'email': 'jessie@villagematernity.com',
        'company': 'Village Maternity',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-523-5167',
        'fax': '',
    },
    {
        # ['Ji Young', 'Wee Tots', 'contact@wee-tots.com', '425-502-7182', '', '']
        'username': 'ji_young',
        'password': 'password',
        # Ji Young,
        'first_name': 'Ji',
        'last_name': 'Young',
        'email': 'contact@wee-tots.com',
        'company': 'Wee Tots',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-502-7182',
        'fax': '',
    },
    {
        # ['John Ross', 'Nordstrom', 'john.ross@nordstrom.com', '206-373-4370', '', '']
        'username': 'john_ross',
        'password': 'password',
        # John Ross,
        'first_name': 'John',
        'last_name': 'Ross',
        'email': 'john.ross@nordstrom.com',
        'company': 'Nordstrom',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-373-4370',
        'fax': '',
    },
    {
        # ['Judie Fletcher', "Fletcher's for Children", 'judie@fletchersforchildren.com', '541-342-5883', '', '']
        'username': 'judie_fletcher',
        'password': 'password',
        # Judie Fletcher,
        'first_name': 'Judie',
        'last_name': 'Fletcher',
        'email': 'judie@fletchersforchildren.com',
        'company': "Fletcher's for Children",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '541-342-5883',
        'fax': '',
    },
    {
        # ['Judy Craven', 'Craven Farm Inc.', 'jmcraven247@gmail.com', '360-568-2601', '', '']
        'username': 'judy_craven',
        'password': 'password',
        # Judy Craven,
        'first_name': 'Judy',
        'last_name': 'Craven',
        'email': 'jmcraven247@gmail.com',
        'company': 'Craven Farm Inc.',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-568-2601',
        'fax': '',
    },
    {
        # ['Judy Matheson', 'J Matheson Gifts', 'info@jmatheson.com', '425-258-2287', '', '']
        'username': 'judy_matheson',
        'password': 'password',
        # Judy Matheson,
        'first_name': 'Judy',
        'last_name': 'Matheson',
        'email': 'info@jmatheson.com',
        'company': 'J Matheson Gifts',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-258-2287',
        'fax': '',
    },
    {
        # ["Julie & Amanda O'Keeffe", 'Step By Step Essentials LLC', 'jokalone@aol.com', '253-370-4728', '', '']
        'username': 'julie_okeeffe',
        'password': 'password',
        # Julie & Amanda O'Keeffe,
        'first_name': 'Julie',
        'last_name': "O'Keeffe",
        'email': 'jokalone@aol.com',
        'company': 'Step By Step Essentials LLC',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '253-370-4728',
        'fax': '',
    },
    {
        # ['Julie Haas', 'Glass Butterfly', 'jhaas987@aol.com', '503-636-9045', '503-635-9754', '']
        'username': 'julie_haas',
        'password': 'password',
        # Julie Haas,
        'first_name': 'Julie',
        'last_name': 'Haas',
        'email': 'jhaas987@aol.com',
        'company': 'Glass Butterfly',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-636-9045',
        'fax': '503-635-9754',
    },
    {
        # ['Karin Leholsky', 'Lollipops', 'karinphoto@mac.com', '206-780-9012', '', '']
        'username': 'karin_leholsky',
        'password': 'password',
        # Karin Leholsky,
        'first_name': 'Karin',
        'last_name': 'Leholsky',
        'email': 'karinphoto@mac.com',
        'company': 'Lollipops',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-780-9012',
        'fax': '',
    },
    {
        # ['Karla Easton', 'Kids Club', 'klseaston@gmail.com', '206-498-0430', '', '']
        'username': 'karla_easton',
        'password': 'password',
        # Karla Easton,
        'first_name': 'Karla',
        'last_name': 'Easton',
        'email': 'klseaston@gmail.com',
        'company': 'Kids Club',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-498-0430',
        'fax': '',
    },
    {
        # ['Kate Etherington', "The Original Children's Shop", 'kateetherington@gmail.com', '206-328-7121', '', '']
        'username': 'kate_etherington',
        'password': 'password',
        # Kate Etherington,
        'first_name': 'Kate',
        'last_name': 'Etherington',
        'email': 'kateetherington@gmail.com',
        'company': "The Original Children's Shop",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-328-7121',
        'fax': '',
    },
    {
        # ['Kathleen M McCrady', 'Wee Ones Reruns', 'k.mccrady@comcast.net', '360-733-6794', '360-510-9320', '']
        'username': 'kathleen_mccrady',
        'password': 'password',
        # Kathleen M McCrady,
        'first_name': 'Kathleen',
        'last_name': 'McCrady',
        'email': 'k.mccrady@comcast.net',
        'company': 'Wee Ones Reruns',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-733-6794',
        'fax': '360-510-9320',
    },
    {
        # ['Katie Matteson', 'Along Comes A Baby', 'admin@alongcomesababy.com', '360-671-5523', '360-671-5534', '']
        'username': 'katie_matteson',
        'password': 'password',
        # Katie Matteson,
        'first_name': 'Katie',
        'last_name': 'Matteson',
        'email': 'admin@alongcomesababy.com',
        'company': 'Along Comes A Baby',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-671-5523',
        'fax': '360-671-5534',
    },
    {
        # ['Kehle Schmeller', 'Posh Baby', 'accounting@poshbaby.com', '503-478-7674', '503-228-8600', '']
        'username': 'kehle_schmeller',
        'password': 'password',
        # Kehle Schmeller,
        'first_name': 'Kehle',
        'last_name': 'Schmeller',
        'email': 'accounting@poshbaby.com',
        'company': 'Posh Baby',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-478-7674',
        'fax': '503-228-8600',
    },
    {
        # ['Kelly Buck', 'Bump Maternity', 'bumpmaternity@comcast.net', '917-608-8907', '', '']
        'username': 'kelly_buck',
        'password': 'password',
        # Kelly Buck,
        'first_name': 'Kelly',
        'last_name': 'Buck',
        'email': 'bumpmaternity@comcast.net',
        'company': 'Bump Maternity',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '917-608-8907',
        'fax': '',
    },
    {
        # ['Kelsey McCallister', 'Village Maternity', 'kelsey@villagematernity.com', '206-523-5167', '', '']
        'username': 'kelsey_mccallister',
        'password': 'password',
        # Kelsey McCallister,
        'first_name': 'Kelsey',
        'last_name': 'McCallister',
        'email': 'kelsey@villagematernity.com',
        'company': 'Village Maternity',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-523-5167',
        'fax': '',
    },
    {
        # ['Kerrie Barreras', "Lil' Britches", 'lil4britches@earthlink.net', '503-492-9378', '503-492-9381', '']
        'username': 'kerrie_barreras',
        'password': 'password',
        # Kerrie Barreras,
        'first_name': 'Kerrie',
        'last_name': 'Barreras',
        'email': 'lil4britches@earthlink.net',
        'company': "Lil' Britches",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-492-9378',
        'fax': '503-492-9381',
    },
    {
        # ['Kim Bremner', "Bubba Loo Children's Boutique", 'kdbremner@shaw.ca', '250 655-7270', '', '']
        'username': 'kim_bremner',
        'password': 'password',
        # Kim Bremner,
        'first_name': 'Kim',
        'last_name': 'Bremner',
        'email': 'kdbremner@shaw.ca',
        'company': "Bubba Loo Children's Boutique",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '250 655-7270',
        'fax': '',
    },
    {
        # ['Kim Slaker', 'Boston Street', 'kimslaker@hotmail.com', '206-634-0580', '', '']
        'username': 'kim_slaker',
        'password': 'password',
        # Kim Slaker,
        'first_name': 'Kim',
        'last_name': 'Slaker',
        'email': 'kimslaker@hotmail.com',
        'company': 'Boston Street',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-634-0580',
        'fax': '',
    },
    {
        # ['Lake Leeman', 'Mini Apple Tree', 'emily@miniappletree.com', '323-384-2257', '', '']
        'username': 'lake_leeman',
        'password': 'password',
        # Lake Leeman,
        'first_name': 'Lake',
        'last_name': 'Leeman',
        'email': 'emily@miniappletree.com',
        'company': 'Mini Apple Tree',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '323-384-2257',
        'fax': '',
    },
    {
        # ['Laura Lee Bosman', 'Along Comes A Baby', 'admin@alongcomesababy.com', '360-671-5523', '360-671-5534', '']
        'username': 'laura_bosman',
        'password': 'password',
        # Laura Lee Bosman,
        'first_name': 'Laura',
        'last_name': 'Bosman',
        'email': 'admin@alongcomesababy.com',
        'company': 'Along Comes A Baby',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-671-5523',
        'fax': '360-671-5534',
    },
    {
        # ['Linda Gislason', 'Deux Chapeaux', '', '360-642-8660', '', '']
        'username': 'linda_gislason',
        'password': 'password',
        # Linda Gislason,
        'first_name': 'Linda',
        'last_name': 'Gislason',
        'email': '',
        'company': 'Deux Chapeaux',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-642-8660',
        'fax': '',
    },
    {
        # ['Lisa Purkerson', 'Sprinkles', 'lisapurk@yahoo.com', '503 586 4662', '', '']
        'username': 'lisa_purkerson',
        'password': 'password',
        # Lisa Purkerson,
        'first_name': 'Lisa',
        'last_name': 'Purkerson',
        'email': 'lisapurk@yahoo.com',
        'company': 'Sprinkles',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503 586 4662',
        'fax': '',
    },
    {
        # ['Lisa Steele', 'Pipsqueaks', 'steeleclub7@gmail.com', '360-600-1590', '', '']
        'username': 'lisa_steele',
        'password': 'password',
        # Lisa Steele,
        'first_name': 'Lisa',
        'last_name': 'Steele',
        'email': 'steeleclub7@gmail.com',
        'company': 'Pipsqueaks',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-600-1590',
        'fax': '',
    },
    {
        # ['Lori Sutich', 'The Shops at Swedish', '', '', '', '']
        'username': 'lori_sutich',
        'password': 'password',
        # Lori Sutich,
        'first_name': 'Lori',
        'last_name': 'Sutich',
        'email': '',
        'company': 'The Shops at Swedish',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '',
        'fax': '',
    },
    {
        # ['Lorinda Laumbach', 'Baby & Beyond', 'lori@babyandbeyond.ca', '780-416-2188', '', '']
        'username': 'lorinda_laumbach',
        'password': 'password',
        # Lorinda Laumbach,
        'first_name': 'Lorinda',
        'last_name': 'Laumbach',
        'email': 'lori@babyandbeyond.ca',
        'company': 'Baby & Beyond',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '780-416-2188',
        'fax': '',
    },
    # {
    #     # ['M. Livingstone', 'Dandelion Kids', 'info@dandelionkids.ca', '604-676-1862', '604-676-1863', '']
    #     'username': 'm_livingstone',
    #     'password': 'password',
    #     # M. Livingstone,
    #     'first_name': 'M',
    #     'last_name': 'Livingstone',
    #     'email': 'info@dandelionkids.ca',
    #     'company': 'Dandelion Kids',
    #     'website': '',
    #     'address': '',
    #     'address2': '',
    #     'city': '',
    #     'state': '',
    #     'zip': '',
    #     'phone': '604-676-1862',
    #     'fax': '604-676-1863',
    # },
    {
        # ['Mako Perera', 'Mako The Children\xef\xbf\xbds Shop', 'makothechildrensshop@gmail.com', '503-274-9081', '', '']
        'username': 'mako_perera',
        'password': 'password',
        # Mako Perera,
        'first_name': 'Mako',
        'last_name': 'Perera',
        'email': 'makothechildrensshop@gmail.com',
        'company': 'Mako The Children?s Shop',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-274-9081',
        'fax': '',
    },
    {
        # ['Malia Keene', 'Magpie Toys and Clothes', 'maliakeene@gmail.com', '206-860-6035', '', '']
        'username': 'malia_keene',
        'password': 'password',
        # Malia Keene,
        'first_name': 'Malia',
        'last_name': 'Keene',
        'email': 'maliakeene@gmail.com',
        'company': 'Magpie Toys and Clothes',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-860-6035',
        'fax': '',
    },
    {
        # ['Marilyn Lamb', 'Cottage Queen', 'lamb@olypen.com', '206-782-0715', '', '']
        'username': 'marilyn_lamb',
        'password': 'password',
        # Marilyn Lamb,
        'first_name': 'Marilyn',
        'last_name': 'Lamb',
        'email': 'lamb@olypen.com',
        'company': 'Cottage Queen',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-782-0715',
        'fax': '',
    },
    {
        # ['Martin Wilter', 'NOK200', 'martinwilter@nok200.com', '206-613-9055', '', '']
        'username': 'martin_wilter',
        'password': 'password',
        # Martin Wilter,
        'first_name': 'Martin',
        'last_name': 'Wilter',
        'email': 'martinwilter@nok200.com',
        'company': 'NOK200',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-613-9055',
        'fax': '',
    },
    {
        # ['Matt and Heather Miller', 'Read Me A Story', 'readmeastory@gmail.com', '360-293-4801', '360-588-0273', '']
        'username': 'matt_miller',
        'password': 'password',
        # Matt and Heather Miller,
        'first_name': 'Matt',
        'last_name': 'Miller',
        'email': 'readmeastory@gmail.com',
        'company': 'Read Me A Story',
        'website': 'http://readmeastoryonline.com/',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-293-4801',
        'fax': '360-588-0273',
    },
    {
        # ['Megan Stuhlberg', "Stuhlberg's", 'megan@stuhlbergs.com', '206-352-2351', '', '']
        'username': 'megan_stuhlberg',
        'password': 'password',
        # Megan Stuhlberg,
        'first_name': 'Megan',
        'last_name': 'Stuhlberg',
        'email': 'megan@stuhlbergs.com',
        'company': "Stuhlberg's",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-352-2351',
        'fax': '',
    },
    {
        # ['Michelle Barnes', 'Charlie Barnes', 'michelle@charliebarneskids.com', '253-509-0449', '', '']
        'username': 'michelle_barnes',
        'password': 'password',
        # Michelle Barnes,
        'first_name': 'Michelle',
        'last_name': 'Barnes',
        'email': 'michelle@charliebarneskids.com',
        'company': 'Charlie Barnes',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '253-509-0449',
        'fax': '',
    },
    {
        # ['Molly Pressy', 'Merry-Go-Round', 'info@merrygoroundkids.com', '425-454-1610', '425-451-8724', '']
        'username': 'molly_pressy',
        'password': 'password',
        # Molly Pressy,
        'first_name': 'Molly',
        'last_name': 'Pressy',
        'email': 'info@merrygoroundkids.com',
        'company': 'Merry-Go-Round',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-454-1610',
        'fax': '425-451-8724',
    },
    {
        # ['Monica Ryan', 'Backcountry Baby', 'monica@backcountry-baby.com', '307-200-4904', '', '']
        'username': 'monica_ryan',
        'password': 'password',
        # Monica Ryan,
        'first_name': 'Monica',
        'last_name': 'Ryan',
        'email': 'monica@backcountry-baby.com',
        'company': 'Backcountry Baby',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '307-200-4904',
        'fax': '',
    },
    {
        # ['Nancy and Sue Keith', 'Bee Bops and Lollipops', 'nancy@bebopsandlollipops.com', '360-568-2333', '', '']
        'username': 'nancy_keith',
        'password': 'password',
        # Nancy and Sue Keith,
        'first_name': 'Nancy',
        'last_name': 'Keith',
        'email': 'nancy@bebopsandlollipops.com',
        'company': 'Bee Bops and Lollipops',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-568-2333',
        'fax': '',
    },
    {
        # ['Natalie Peters-Martin', 'Posh Baby', 'natalie@poshbaby.com', '503-478-7674', '503-228-8600', '']
        'username': 'natalie_petersmartin',
        'password': 'password',
        # Natalie Peters-Martin,
        'first_name': 'Natalie',
        'last_name': 'Peters-Martin',
        'email': 'natalie@poshbaby.com',
        'company': 'Posh Baby',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-478-7674',
        'fax': '503-228-8600',
    },
    {
        # ['Pati Willis', 'Ositos', 'ositostoys@yahoo.com', '360-378-4320', '360-378-4147', '']
        'username': 'pati_willis',
        'password': 'password',
        # Pati Willis,
        'first_name': 'Pati',
        'last_name': 'Willis',
        'email': 'ositostoys@yahoo.com',
        'company': 'Ositos',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-378-4320',
        'fax': '360-378-4147',
    },
    {
        # ['Patricia Tasakos', 'Tessa Marie Childrens Boutque', 'tessamarieboutique@yahoo.com', '425-359-6998', '', '']
        'username': 'patricia_tasakos',
        'password': 'password',
        # Patricia Tasakos,
        'first_name': 'Patricia',
        'last_name': 'Tasakos',
        'email': 'tessamarieboutique@yahoo.com',
        'company': 'Tessa Marie Childrens Boutque',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-359-6998',
        'fax': '',
    },
    {
        # ['Rosalee Rester', 'Baby Wit', 'mom@babywit.com', '503-284-2283', '', '']
        'username': 'rosalee_rester',
        'password': 'password',
        # Rosalee Rester,
        'first_name': 'Rosalee',
        'last_name': 'Rester',
        'email': 'mom@babywit.com',
        'company': 'Baby Wit',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-284-2283',
        'fax': '',
    },
    {
        # ['Sandy Willmett', 'Baby-n-Me', 'sandy@babynme.comcastbiz.net', '360-675-8816', '', '']
        'username': 'sandy_willmett',
        'password': 'password',
        # Sandy Willmett,
        'first_name': 'Sandy',
        'last_name': 'Willmett',
        'email': 'sandy@babynme.comcastbiz.net',
        'company': 'Baby-n-Me',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-675-8816',
        'fax': '',
    },
    {
        # ['Sarah Furstanberg', 'Clover', 'clover@clovertoys.com', '206-782-0715', '', '']
        'username': 'sarah_furstanberg',
        'password': 'password',
        # Sarah Furstanberg,
        'first_name': 'Sarah',
        'last_name': 'Furstanberg',
        'email': 'clover@clovertoys.com',
        'company': 'Clover',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-782-0715',
        'fax': '',
    },
    {
        # ['Sarah Shaoul', 'Black Wagon', 'sales@blackwagon.com', '503-916-0000', '', '']
        'username': 'sarah_shaoul',
        'password': 'password',
        # Sarah Shaoul,
        'first_name': 'Sarah',
        'last_name': 'Shaoul',
        'email': 'sales@blackwagon.com',
        'company': 'Black Wagon',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-916-0000',
        'fax': '',
    },
    {
        # ['Sarah Stegner', 'Again & a Gain', 'justasksar@gmail.com', '206-933-2060', '', '']
        'username': 'sarah_stegner',
        'password': 'password',
        # Sarah Stegner,
        'first_name': 'Sarah',
        'last_name': 'Stegner',
        'email': 'justasksar@gmail.com',
        'company': 'Again & a Gain',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-933-2060',
        'fax': '',
    },
    {
        # ['Shamaine Coffee', 'Coffee Kids', 'coffeekidsportland@gmail.com', '503-310-0651', '', '']
        'username': 'shamaine_coffee',
        'password': 'password',
        # Shamaine Coffee,
        'first_name': 'Shamaine',
        'last_name': 'Coffee',
        'email': 'coffeekidsportland@gmail.com',
        'company': 'Coffee Kids',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-310-0651',
        'fax': '',
    },
    {
        # ['Sharon Coshow', 'Deux Chapeaux', '', '360-642-8660', '', '']
        'username': 'sharon_coshow',
        'password': 'password',
        # Sharon Coshow,
        'first_name': 'Sharon',
        'last_name': 'Coshow',
        'email': '',
        'company': 'Deux Chapeaux',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-642-8660',
        'fax': '',
    },
    {
        # ['Sheila Barichello', 'Trendy Trikes Boutique', '', '', '', '']
        'username': 'sheila_barichello',
        'password': 'password',
        # Sheila Barichello,
        'first_name': 'Sheila',
        'last_name': 'Barichello',
        'email': '',
        'company': 'Trendy Trikes Boutique',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '',
        'fax': '',
    },
    {
        # ['Shoko Yasuda', 'Market To Japan LLC.', 'shoko@markettojapan.com', '425-378-9216', '', '']
        'username': 'shoko_yasuda',
        'password': 'password',
        # Shoko Yasuda,
        'first_name': 'Shoko',
        'last_name': 'Yasuda',
        'email': 'shoko@markettojapan.com',
        'company': 'Market To Japan LLC.',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '425-378-9216',
        'fax': '',
    },
    {
        # ['Stefanie Missler', 'Dandelion Kids', 'info@dandelionkids.ca', '604-676-1862', '604-676-1863', '']
        'username': 'stefanie_missler',
        'password': 'password',
        # Stefanie Missler,
        'first_name': 'Stefanie',
        'last_name': 'Missler',
        'email': 'info@dandelionkids.ca',
        'company': 'Dandelion Kids',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '604-676-1862',
        'fax': '604-676-1863',
    },
    {
        # ['Susan Arefi', 'Kids on 45th', 'kidson45th@gmail.com', '206-633-5437', '', '']
        'username': 'susan_arefi',
        'password': 'password',
        # Susan Arefi,
        'first_name': 'Susan',
        'last_name': 'Arefi',
        'email': 'kidson45th@gmail.com',
        'company': 'Kids on 45th',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-633-5437',
        'fax': '',
    },
    {
        # ['Susan Baritelle', 'Dungeness Kids Co.', 'susan@dungenesskids.com', '360-582-1700', '', '']
        'username': 'susan_baritelle',
        'password': 'password',
        # Susan Baritelle,
        'first_name': 'Susan',
        'last_name': 'Baritelle',
        'email': 'susan@dungenesskids.com',
        'company': 'Dungeness Kids Co.',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-582-1700',
        'fax': '',
    },
    {
        # ['Susan Lewis', "Dandelion Wishes Children's Apparel", 'susanlewis111@gmail.com', '(253)549-3709', '', '']
        'username': 'susan_lewis',
        'password': 'password',
        # Susan Lewis,
        'first_name': 'Susan',
        'last_name': 'Lewis',
        'email': 'susanlewis111@gmail.com',
        'company': "Dandelion Wishes Children's Apparel",
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '(253)549-3709',
        'fax': '',
    },
    {
        # ['Susan Westcott', 'Baby Phases Tot 2 Teen', 'babyphasestot2teen@hotmail.com', '541-389-3549', '541-389-8923', '']
        'username': 'susan_westcott',
        'password': 'password',
        # Susan Westcott,
        'first_name': 'Susan',
        'last_name': 'Westcott',
        'email': 'babyphasestot2teen@hotmail.com',
        'company': 'Baby Phases Tot 2 Teen',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '541-389-3549',
        'fax': '541-389-8923',
    },
    {
        'username': 'molly_ryan',
        'password': 'password',
        'first_name': 'Molly',
        'last_name': 'Ryan',
        'email': 'babyphasestot2teen@hotmail.com',
        'company': 'Baby Phases Tot 2 Teen',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '541-389-3549',
        'fax': '541-389-8923',
    },
    {
        # ['Tamar Felton', 'Star Store', 'starstore@whidbey.com', '360-221-5223', '360-221-5224', '']
        'username': 'tamar_felton',
        'password': 'password',
        # Tamar Felton,
        'first_name': 'Tamar',
        'last_name': 'Felton',
        'email': 'starstore@whidbey.com',
        'company': 'Star Store',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '360-221-5223',
        'fax': '360-221-5224',
    },
    {
        # ['Terry Herman', 'Metropolis', 'pvtravel@aol.com', '206-782-7002', '', '']
        'username': 'terry_herman',
        'password': 'password',
        # Terry Herman,
        'first_name': 'Terry',
        'last_name': 'Herman',
        'email': 'pvtravel@aol.com',
        'company': 'Metropolis',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-782-7002',
        'fax': '',
    },
    {
        # ['Tessa Tasakos', 'Tessa Marie Childrens Boutque', 'tessamarieboutique@yahoo.com', '509-888-0623', '', '']
        'username': 'tessa_tasakos',
        'password': 'password',
        # Tessa Tasakos,
        'first_name': 'Tessa',
        'last_name': 'Tasakos',
        'email': 'tessamarieboutique@yahoo.com',
        'company': 'Tessa Marie Childrens Boutque',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '509-888-0623',
        'fax': '',
    },
    {
        # ['Theresa and John Keith', 'Hennie McPennie', 'henniemcpennie@gmail.com', '206-232-0495', '', '']
        'username': 'theresa_keith',
        'password': 'password',
        # Theresa and John Keith,
        'first_name': 'Theresa',
        'last_name': 'Keith',
        'email': 'henniemcpennie@gmail.com',
        'company': 'Hennie McPennie',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-232-0495',
        'fax': '',
    },
    {
        # ['Tiffany Johnson', 'SunnyPatch Boutique', 'sunnypatchboutique@yahoo.com', '541-928-2272', '', '']
        'username': 'tiffany_johnson',
        'password': 'password',
        # Tiffany Johnson,
        'first_name': 'Tiffany',
        'last_name': 'Johnson',
        'email': 'sunnypatchboutique@yahoo.com',
        'company': 'SunnyPatch Boutique',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '541-928-2272',
        'fax': '',
    },
    {
        # ['Tristine Drennan', 'Let It Rain', 'tristine@let-it-rain.com', '503-325-7728', '503-325-0667', '']
        'username': 'tristine_drennan',
        'password': 'password',
        # Tristine Drennan,
        'first_name': 'Tristine',
        'last_name': 'Drennan',
        'email': 'tristine@let-it-rain.com',
        'company': 'Let It Rain',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '503-325-7728',
        'fax': '503-325-0667',
    },
    {
        # ['Wendy Powell', 'Childish Things', 'info@childishthingsseattle.net', '206-789-1498', '', '']
        'username': 'wendy_powell',
        'password': 'password',
        # Wendy Powell,
        'first_name': 'Wendy',
        'last_name': 'Powell',
        'email': 'info@childishthingsseattle.net',
        'company': 'Childish Things',
        'website': '',
        'address': '',
        'address2': '',
        'city': '',
        'state': '',
        'zip': '',
        'phone': '206-789-1498',
        'fax': '',
    },
]
